In [ ]:
from sklearn.model_selection import KFold
fold=KFold(n_splits=4)
fold

KFold(n_splits=4, random_state=None, shuffle=False)

In [ ]:
import numpy as np
data=np.arange(1,16)
data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
for train_index,test_index in fold.split(data):
  print(train_index,test_index)

[ 3  4  5  6  7  8  9 10 11 12 13 14] [0 1 2]
[ 0  1  2  6  7  8  9 10 11 12 13 14] [3 4 5]
[ 0  1  2  3  4  5  9 10 11 12 13 14] [6 7 8]
[ 0  1  2  3  4  5  6  7  8 12 13 14] [ 9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11] [12 13 14]


# load digits

In [ ]:
from sklearn.model_selection import StratifiedKFold
s_fold=StratifiedKFold(n_splits=4)
s_fold

StratifiedKFold(n_splits=4, random_state=None, shuffle=False)

In [ ]:
def score_model(model,xtrain,xtest,ytrain,ytest):
  model.fit(xtrain,ytrain)
  return model.score(xtest,ytest)

In [ ]:
from sklearn.datasets import load_digits
digits=load_digits()
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [ ]:
dig_data=digits.data
dig_target=digits.target

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.model_selection import KFold
fold=KFold()

In [ ]:
l_score=[]
rf_score=[]
svc_score=[]

In [ ]:
for train_index,test_index in fold.split(dig_data,dig_target):
  xtrain,xtest=digits.data[train_index],digits.data[test_index]
  ytrain,ytest=digits.target[train_index],digits.target[test_index]
  l_score.append(score_model(LogisticRegression(max_iter=500),xtrain,xtest,ytrain,ytest))
  rf_score.append(score_model(RandomForestClassifier(),xtrain,xtest,ytrain,ytest))
  svc_score.append(score_model(SVC(),xtrain,xtest,ytrain,ytest))

In [ ]:
print(l_score)
print(rf_score)
print(svc_score)

[0.9277777777777778, 0.875, 0.9415041782729805, 0.9387186629526463, 0.9052924791086351]
[0.9416666666666667, 0.8916666666666667, 0.9610027855153204, 0.9637883008356546, 0.924791086350975]
[0.9694444444444444, 0.9472222222222222, 0.9832869080779945, 0.9888579387186629, 0.9415041782729805]


In [ ]:
from sklearn.datasets import load_digits
digits=load_digits()
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [ ]:
from sklearn.model_selection import cross_val_score
l_score=cross_val_score(LogisticRegression(max_iter=500),X=digits.data,y=digits.target)
svc_score=cross_val_score(SVC(),X=digits.data,y=digits.target)
rf_score=cross_val_score(RandomForestClassifier(),X=digits.data,y=digits.target)

In [ ]:
print(l_score)
print(rf_score)
print(svc_score)

[0.92222222 0.87222222 0.94150418 0.94150418 0.89693593]
[0.93055556 0.9        0.96100279 0.96657382 0.91922006]
[0.96111111 0.94444444 0.98328691 0.98885794 0.93871866]


# load iris

In [ ]:
from sklearn.model_selection import StratifiedKFold
s_fold=StratifiedKFold(n_splits=4)
s_fold

StratifiedKFold(n_splits=4, random_state=None, shuffle=False)

In [ ]:
def score_model(model,xtrain,xtest,ytrain,ytest):
  model.fit(xtrain,ytrain)
  return model.score(xtest,ytest)

In [ ]:
from sklearn.datasets import load_iris
iris=load_iris()
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [ ]:
dig_data=iris.data
dig_target=iris.target

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.model_selection import KFold
fold=KFold()

In [ ]:
l_score=[]
rf_score=[]
svc_score=[]

In [ ]:
for train_index,test_index in s_fold.split(dig_data,dig_target):
  xtrain,xtest=digits.data[train_index],digits.data[test_index]
  ytrain,ytest=digits.target[train_index],digits.target[test_index]
  l_score.append(score_model(LogisticRegression(max_iter=500),xtrain,xtest,ytrain,ytest))
  rf_score.append(score_model(RandomForestClassifier(),xtrain,xtest,ytrain,ytest))
  svc_score.append(score_model(SVC(),xtrain,xtest,ytrain,ytest))

In [ ]:
print(l_score)
print(rf_score)
print(svc_score)

[0.9473684210526315, 0.9210526315789473, 0.972972972972973, 0.972972972972973]
[0.9210526315789473, 0.9473684210526315, 0.972972972972973, 0.9459459459459459]
[0.9473684210526315, 0.9736842105263158, 1.0, 0.972972972972973]


In [ ]:
y=dig_target
x=dig_data

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=.3)
model=SVC()
model.fit(xtrain,ytrain)
model.predict(xtest)

array([0, 2, 1, 2, 2, 0, 2, 1, 0, 1, 0, 0, 0, 2, 1, 0, 0, 0, 0, 2, 2, 2,
       2, 1, 1, 0, 1, 2, 2, 0, 1, 0, 0, 1, 2, 1, 1, 0, 2, 2, 0, 0, 1, 1,
       1])

In [ ]:
model.score(xtest,ytest)

1.0

# titanic

In [ ]:
import pandas as pd
data=pd.read_csv('/content/titanic.csv')
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [ ]:
from sklearn.preprocessing import LabelEncoder
labelencoder=LabelEncoder()
labelencoder

LabelEncoder()

In [ ]:
data['Sex']=labelencoder.fit_transform(data['Sex'])
data['Embarked']=labelencoder.fit_transform(data['Embarked'])


In [ ]:
data['Age'].fillna(data['Age'].mean(),inplace=True)
data['Embarked'].fillna(data['Embarked'].median(),inplace=True)


<ipython-input-105-800335a434f3>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Age'].fillna(data['Age'].mean(),inplace=True)
<ipython-input-105-800335a434f3>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try

In [ ]:
del data['Ticket']
del data['Name']
del data['Cabin']

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Sex          891 non-null    int64  
 4   Age          891 non-null    float64
 5   SibSp        891 non-null    int64  
 6   Parch        891 non-null    int64  
 7   Fare         891 non-null    float64
 8   Embarked     891 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 62.8 KB


In [ ]:
from sklearn.model_selection import StratifiedKFold
s_fold=StratifiedKFold(n_splits=4)
s_fold

StratifiedKFold(n_splits=4, random_state=None, shuffle=False)

In [ ]:
y=data[['Survived']]
x=data[['Pclass','Sex','Age','SibSp','Parch','Fare','Embarked']]

In [ ]:
def score_model(model,xtrain,xtest,ytrain,ytest):
    model.fit(xtrain,ytrain)
    return model.score(xtest,ytest)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

In [ ]:
l_score = []
rf_score = []
svc_score = []

In [ ]:
for train_index,test_index in s_fold.split(x,y):
  xtrain,xtest=x.iloc[train_index],x.iloc[test_index] # Use .iloc[] for row-based indexing
  ytrain,ytest=y.iloc[train_index],y.iloc[test_index] # Use .iloc[] for row-based indexing
  l_score.append(score_model(LogisticRegression(max_iter=500),xtrain,xtest,ytrain,ytest))
  rf_score.append(score_model(RandomForestClassifier(),xtrain,xtest,ytrain,ytest))
  svc_score.append(score_model(SVC(),xtrain,xtest,ytrain,ytest))

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.11/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for ex

In [ ]:
print(l_score)
print(rf_score)
print(svc_score)

[0.7802690582959642, 0.8026905829596412, 0.7757847533632287, 0.8198198198198198]
[0.7488789237668162, 0.8340807174887892, 0.8161434977578476, 0.8198198198198198]
[0.5829596412556054, 0.7174887892376681, 0.6681614349775785, 0.6891891891891891]


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=.3)
model=RandomForestClassifier()
model.fit(xtrain,ytrain)
model.predict(xtest)

/usr/local/lib/python3.11/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


array([1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0])

In [ ]:
model.score(xtest,ytest)

0.8246268656716418

# loan data 1

In [ ]:
import pandas as pd
from sklearn.model_selection import KFold
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder

# Load the dataset
df = pd.read_csv('/content/loan_data.csv')
df

person_age person_gender person_education  person_income  \
0            22.0        female           Master        71948.0   
1            21.0        female      High School        12282.0   
2            25.0        female      High School        12438.0   
3            23.0        female         Bachelor        79753.0   
4            24.0          male           Master        66135.0   
...           ...           ...              ...            ...   
44995        27.0          male        Associate        47971.0   
44996        37.0        female        Associate        65800.0   
44997        33.0          male        Associate        56942.0   
44998        29.0          male         Bachelor        33164.0   
44999        24.0          male      High School        51609.0   

       person_emp_exp person_home_ownership  loan_amnt        loan_intent  \
0                   0                  RENT    35000.0           PERSONAL   
1                   0                   OWN     1000.0          EDUCATION   
2                   3              MORTGAGE     5500.0            MEDICAL   
3                   0                  RENT    35000.0            MEDICAL   
4                   1                  RENT    35000.0            MEDICAL   
...               ...                   ...        ...                ...   
44995               6                  RENT    15000.0            MEDICAL   
44996              17                  RENT     9000.0    HOMEIMPROVEMENT   
44997               7                  RENT     2771.0  DEBTCONSOLIDATION   
44998               4                  RENT    12000.0          EDUCATION   
44999               1                  RENT     6665.0  DEBTCONSOLIDATION   

       loan_int_rate  loan_percent_income  cb_person_cred_hist_length  \
0              16.02                 0.49                         3.0   
1              11.14                 0.08                         2.0   
2              12.87                 0.44                         3.0   
3              15.23                 0.44                         2.0   
4              14.27                 0.53                         4.0   
...              ...                  ...                         ...   
44995          15.66                 0.31                         3.0   
44996          14.07                 0.14                        11.0   
44997          10.02                 0.05                        10.0   
44998          13.23                 0.36                         6.0   
44999          17.05                 0.13                         3.0   

       credit_score previous_loan_defaults_on_file  loan_status  
0               561                             No            1  
1               504                            Yes            0  
2               635                             No            1  
3               675                             No            1  
4               586                             No            1  
...             ...                            ...          ...  
44995           645                             No            1  
44996           621                             No            1  
44997           668                             No            1  
44998           604                             No            1  
44999           628                             No            1  

[45000 rows x 14 columns]

In [ ]:


df = df.dropna()  # Drop rows with missing values for now
le = LabelEncoder()
for column in df.columns:
    if df[column].dtype == 'object':
        df[column] = le.fit_transform(df[column])

# Separate features and target
X = df.drop('loan_status', axis=1)
y = df['loan_status']

# Initialize KFold
kf = KFold(n_splits=5, shuffle=True, random_state=42)

# Initialize the model
model = LogisticRegression()

# Loop through KFold splits
for fold, (train_index, test_index) in enumerate(kf.split(X), 1):
    print(f"\nFold {fold}")

    # Split data
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]

    # Train model
    model.fit(X_train, y_train)

    # Predict
    y_pred = model.predict(X_test)

    # Evaluate
    acc = accuracy_score(y_test, y_pred)
    print("Accuracy:", acc)



Fold 1


/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Accuracy: 0.8284444444444444

Fold 2


/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Accuracy: 0.831

Fold 3


/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Accuracy: 0.8245555555555556

Fold 4


/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Accuracy: 0.8423333333333334

Fold 5
Accuracy: 0.8244444444444444


/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


# loan data 2

In [ ]:
import pandas as pd
from sklearn.model_selection import KFold
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
import numpy as np

# Load and preprocess the dataset
df = pd.read_csv('/content/loan_data.csv')
df = df.dropna()  # Drop rows with missing values

# Encode categorical features
le = LabelEncoder()
for column in df.columns:
    if df[column].dtype == 'object':
        df[column] = le.fit_transform(df[column])

# Split features and target
X = df.drop('loan_status', axis=1)
y = df['loan_status']

# KFold setup
kf = KFold(n_splits=5, shuffle=True, random_state=42)
model = LogisticRegression()

# Track best fold data
best_accuracy = 0
best_fold = -1


# Save best fold's data
best_X_train = None
best_y_train = None
best_X_test = None
best_y_test = None
best_y_pred = None

# Loop over each fold
for fold, (train_index, test_index) in enumerate(kf.split(X), 1):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]

    # Train model
    model.fit(X_train, y_train)

    # Predict
    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    print(f"Fold {fold} Accuracy: {acc}")

    # Update best fold
    if acc > best_accuracy:
        best_accuracy = acc
        best_fold = fold
        best_X_train = X_train
        best_y_train = y_train
        best_X_test = X_test
        best_y_test = y_test
        best_y_pred = y_pred

# Output best fold details
print(f"\n Best Fold: {best_fold} with Accuracy: {best_accuracy}")




/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Fold 1 Accuracy: 0.8284444444444444


/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Fold 2 Accuracy: 0.831


/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Fold 3 Accuracy: 0.8245555555555556


/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Fold 4 Accuracy: 0.8423333333333334
Fold 5 Accuracy: 0.8244444444444444

 Best Fold: 4 with Accuracy: 0.8423333333333334


/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [ ]:
model = LogisticRegression()
model.fit(best_X_train,best_y_train)
model.score(best_X_test,best_y_test)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.8423333333333334