In [ ]:
pip install tensorflow

In [ ]:
import tensorflow as tf
print('Tensorflow version:',tf.__version__)
print('keras version',tf.keras.__version__)

Tensorflow version: 2.18.0
keras version 3.8.0


How to Build a Model in Keras?
Keras provides two main ways to build models:
*Sequential API
*Functional API

Sequential API are easy to work with models with a single input and output and a linear stack of layers.

 Functional API can be used for models that require multiple inputs and outputs, or layers have multiple inputs or outputs.

# sequential API

In [ ]:
from keras.models import Sequential
from keras.layers import Dense,Activation
model=Sequential()
model.add(Dense(units=64,input_dim=100))
model.add(Activation('relu'))
model.add(Dense(units=10))
model.add(Activation('softmax'))

# functional API

In [ ]:
from keras.layers import Input,Dense,concatenate
from keras.models import Model
input1=Input(shape=(100,))
input2=Input(shape=(50,))
hidden1=Dense(64,activation='relu')(input1)
hidden2=Dense(32,activation='relu')(input2)
merged=concatenate([hidden1,hidden2])
output=Dense(10,activation='softmax')(merged)
model=Model(inputs=[input1,input2],outputs=output)

# Tensorflow

## tensor

### scalar(0Dimension tensor)

In [ ]:
# a single number (eg 5)
import tensorflow as tf
scalar=tf.constant(5)
print(scalar)

tf.Tensor(5, shape=(), dtype=int32)


### vector(1D tensor)

In [ ]:
#A vector is a one-dimensional tensor (like an array). Example: [1, 2, 3]
import tensorflow as tf
vector=tf.constant([5,10,15,20])
vector

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 5, 10, 15, 20], dtype=int32)>

### Matrix (2D Tensor)

In [ ]:
#A matrix is a two-dimensional tensor (rows and columns).
import tensorflow as tf
matrix=tf.constant([[1,2,3],[4,5,6]])
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

### 3D Tensor

In [ ]:
#A 3D tensor is like a collection of matrices stacked together
tensor3d=tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]])
tensor3d

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int32)>

### Higher-Dimensional Tensors (4D, 5D, etc.)

In [ ]:
#Used in deep learning for images, videos, and complex models.
#Example of a 4D Tensor:
#Used for image processing with shape (batch_size, height, width, channels).
tensor4d=tf.constant([[[[1], [2]], [[3], [4]]], [[[5], [6]], [[7], [8]]]])
print(tensor4d)

tf.Tensor(
[[[[1]
   [2]]

  [[3]
   [4]]]


 [[[5]
   [6]]

  [[7]
   [8]]]], shape=(2, 2, 2, 1), dtype=int32)


# TENSOR FUNCTIONS

## tf.constant()

In [ ]:
#Creates a constant tensor
tensor = tf.constant([[1, 2], [3, 4]])
print(tensor)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


## tf.zeros()

In [ ]:
#Creates a tensor filled with zeros
import tensorflow as tf
one_tensor=tf.ones([2,3])
one_tensor

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

## tf.random.uniform()

In [ ]:
#Creates a tensor with random values
randomtensor=tf.random.uniform([2,2],minval=0,maxval=10,dtype=tf.int32)
randomtensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[7, 3],
       [5, 5]], dtype=int32)>

## tf.shape()

In [ ]:
#Returns the shape of a tensor
tensor=tf.constant([[1,2],[3,4]])
print(tf.shape(tensor))

tf.Tensor([2 2], shape=(2,), dtype=int32)


# mathematical operation

1.tf.add() - Element-wise addition

2.tf.subtract() - Element-wise subtraction

3.tf.multiply() - Element-wise multiplication

4.tf.divide() - Element-wise division

5.tf.matmul() - Matrix multiplication

In [ ]:
import tensorflow as tf
a=tf.constant([1,2,3])
b=tf.constant([4,5,6])
c=tf.add(a,b)
c

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 7, 9], dtype=int32)>

In [ ]:
import tensorflow as tf
a=tf.constant([1,2,3])
b=tf.constant([4,5,6])
c=tf.subtract(a,b)
c

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-3, -3, -3], dtype=int32)>

In [ ]:
import tensorflow as tf
a=tf.constant([1,2,3])
b=tf.constant([4,5,6])
c=tf.multiply(a,b)
c

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 4, 10, 18], dtype=int32)>

In [ ]:
import tensorflow as tf
a=tf.constant([1,2,3])
b=tf.constant([4,5,6])
c=tf.divide(a,b)
c

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.25, 0.4 , 0.5 ])>

In [ ]:
matrix1=tf.constant([[1,2],[3,4]])
matrix2=tf.constant([[5,6],[7,8]])
result=tf.matmul(matrix1,matrix2)
print(result)

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


# Reshaping & Manipulating Tensors

tf.reshape() - Changes tensor shap

tf.transpose() - Transposes a matrix

tf.squeeze() - Removes dimensions of size 1

tf.expand_dims() - Adds a new dimension

In [ ]:
import tensorflow as tf
tensor=tf.constant([1,2,3,4,5,6])
reshaped_tensor=tf.reshape(tensor,[2,3])
print(reshaped_tensor)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [ ]:
import tensorflow as tf
matrix=tf.constant([[1,2,3],[4,5,6]])
transposed=tf.transpose(matrix)
transposed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>

In [ ]:
import tensorflow as tf
tensor=tf.constant([[[1],[2],[3]]])
squeezed=tf.squeeze(tensor)
squeezed

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [ ]:
import tensorflow as tf
tensor=tf.constant([1,2,3])
expanded=tf.expand_dims(tensor,axis=1)
expanded

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3]], dtype=int32)>

# Aggregation Functions (Summarizing Data)

tf.reduce_sum() - Computes sum of all elements

tf.reduce_mean() - Computes mean (average)

tf.reduce_max() & tf.reduce_min() - Finds max/min

In [ ]:
import tensorflow as tf
tensor=tf.constant([[1,2],[3,4]])
sum=tf.reduce_sum(tensor)
sum

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [ ]:
mean_result=tf.reduce_mean(tensor)
mean_result

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
max_result=tf.reduce_max(tensor)
max_result

<tf.Tensor: shape=(), dtype=int32, numpy=4>

# Indexing & Slicing Tensors

In [1]:
import tensorflow as tf
tensor=tf.constant([1,2,3,4,5])
print(tensor[0])
print(tensor[-1])

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)


In [2]:
import tensorflow as tf
tensor=tf.constant([10,20,30,40,50])
print(tensor[1:4])

tf.Tensor([20 30 40], shape=(3,), dtype=int32)


# Broadcasting in Tensors

In [3]:
import tensorflow as tf
tensor1 = tf.constant([[1, 2, 3]])
tensor2 = tf.constant([[1], [2], [3]])

result = tensor1 + tensor2
print(result)

tf.Tensor(
[[2 3 4]
 [3 4 5]
 [4 5 6]], shape=(3, 3), dtype=int32)
