In [13]:
import numpy as np
arr=[1,2,3,4]
print(arr)
print(type(arr))


[1, 2, 3, 4]
<class 'list'>


In [16]:
arr=np.array([1,2,3,4])
print(type(arr))
arr1=np.array((1,2,3,4))
print(type(arr1))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [7]:
arr=np.array(42)
print(arr)


42


In [9]:
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [10]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [11]:
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [12]:
a=np.array(42)
b=np.array([1,2,3,4])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [20]:
arr=np.array([[1,2,3,4],[5,6,7,8]],ndmin=6)
print(arr)
print("number:",arr.ndim)

[[[[[[1 2 3 4]
     [5 6 7 8]]]]]]
number: 6
